// Generates typed AnyCable client code from the cable AsyncAPI documents.
//
// For each configured document it emits, under the output directory:
//   models/*.ts        — message payload interfaces + enums, the latter as string
//                        literal unions (via @asyncapi/modelina)
//   channels/*.ts      — one `Channel<Params, Message>` subclass per operation;
//                        depends ONLY on @anycable/core (platform-agnostic — works
//                        on web AND React Native) + the models. Together with
//                        models/ this is the portable, app-free core.
//   runtime.ts         — the framework preset's subscribe+lifecycle helper. The
//                        ONLY file with the cable seam: it imports the cable
//                        provider from a CONFIGURABLE path (Orval-mutator style).
//   composables/*.ts   — per-channel `useXChannel(handlers)` sugar delegating to
//                        runtime; imports only ../runtime + its own class.
//   index.ts           — barrel re-exporting everything
//
// The framework preset is per-target (`output.preset`, default "vue"): "vue"
// emits Vue composables (onScopeDispose); "react" emits React hooks (useEffect)
// for React Native / React consumers. Only the preset (runtime + wrapper) differs
// — the channel classes + models are shared across presets.
//
// Targets (inputs, output dirs, cable seam, preset) come from a cable.config file
// in the consuming project — the AnyCable analog of orval.config.ts. The CLI
// (bin/cli.mjs) loads that config and calls generateAll(); generateOne/generateAll
// are also exported for programmatic use.
import {
  TypeScriptFileGenerator,
  typeScriptDefaultModelNameConstraints,
  typeScriptDefaultPropertyKeyConstraints,
} from "@asyncapi/modelina";
import { Parser } from "@asyncapi/parser";
import fs from "node:fs/promises";
import path from "node:path";

/** Fallback cable seam when a target omits `output.cable`. */
const DEFAULT_CABLE = { path: "../internalCableClient", name: "getCable" };

const BANNER =
  "// AUTO-GENERATED by asyncapi-cable from the cable AsyncAPI documents.\n" +
  "// Do not edit by hand — regenerate with the asyncapi-cable CLI.\n";

const CHANNEL_HANDLERS = `type ChannelMessage<C> = C extends Channel<infer _P, infer M> ? M : never;

export interface ChannelHandlers<M> {
  onMessage: (data: M) => void;
  onConnect?: () => void;
  onDisconnect?: () => void;
}`;

/** The generated runtime — the one file that references the cable seam. Per preset. */
function renderRuntime(cable, preset) {
  if (preset === "react") {
    return `${BANNER}
import type { Channel } from "@anycable/core";
import { useEffect, useRef } from "react";
import { ${cable.name} } from "${cable.path}";

${CHANNEL_HANDLERS}

/**
 * Subscribe a channel for the lifetime of the component. \`factory\` builds the
 * channel; handlers are read through a ref so re-renders don't resubscribe.
 */
export function useChannelSubscription<C extends Channel>(
  factory: () => C,
  handlers: ChannelHandlers<ChannelMessage<C>>,
): void {
  const handlersRef = useRef(handlers);
  handlersRef.current = handlers;

  useEffect(() => {
    const channel = factory();
    ${cable.name}().subscribe(channel);
    const unbind = [
      channel.on("message", (data) =>
        handlersRef.current.onMessage(data as ChannelMessage<C>)
      ),
      channel.on("connect", () => handlersRef.current.onConnect?.()),
      channel.on("disconnect", () => handlersRef.current.onDisconnect?.()),
    ];
    return () => {
      unbind.forEach((off) => off());
      channel.disconnect();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
}
`;
  }

  return `${BANNER}
import type { Channel } from "@anycable/core";
import { getCurrentScope, onScopeDispose } from "vue";
import { ${cable.name} } from "${cable.path}";

${CHANNEL_HANDLERS}

/** Subscribe a channel via the app cable and tear it down with the effect scope. */
export function subscribeChannel<C extends Channel>(
  channel: C,
  handlers: ChannelHandlers<ChannelMessage<C>>,
): C {
  ${cable.name}().subscribe(channel);
  channel.on("message", (data) => handlers.onMessage(data as ChannelMessage<C>));
  if (handlers.onConnect) channel.on("connect", handlers.onConnect);
  if (handlers.onDisconnect) channel.on("disconnect", handlers.onDisconnect);
  if (getCurrentScope()) onScopeDispose(() => channel.disconnect());
  return channel;
}
`;
}

/** True for an http(s) URL input (fetched over HTTP) vs. a local file path (read from disk). */
export function isRemoteInput(input) {
  return /^https?:\/\//i.test(input);
}

/** Load the raw AsyncAPI document from a URL (fetched) or a local file path. */
async function loadRawDocument(source) {
  if (isRemoteInput(source)) {
    const res = await fetch(source);
    if (!res.ok) {
      throw new Error(
        `Failed to fetch ${source}: ${res.status} ${res.statusText}`
      );
    }
    return res.text();
  }
  return fs.readFile(source, "utf8");
}

async function parseDocument(source) {
  const parser = new Parser();
  const raw = await loadRawDocument(source);
  const { document, diagnostics } = await parser.parse(raw);
  if (!document) {
    const errors = diagnostics
      .filter((d) => d.severity === 0)
      .map((d) => `  - ${d.message} (${d.path?.join("/")})`)
      .join("\n");
    throw new Error(`Failed to parse ${source}:\n${errors}`);
  }
  return document;
}

/**
 * The message schemas carry an `allOf`/`if`/`then` block encoding "if `exception`
 * is present then `status` is `failed`". That constraint is not representable in
 * TypeScript, and Modelina mis-flattens the `then` branch into the base schema
 * (turning `status: string` into the literal `'failed'`). Strip conditionals so
 * the generated types reflect the unconstrained shape.
 */
export function stripConditionals(json) {
  const schemas = json?.components?.schemas ?? {};
  for (const schema of Object.values(schemas)) {
    if (Array.isArray(schema.allOf)) {
      schema.allOf = schema.allOf.filter(
        (sub) => !("if" in sub || "then" in sub || "else" in sub)
      );
      if (schema.allOf.length === 0) delete schema.allOf;
    }
    delete schema.if;
    delete schema.then;
    delete schema.else;
  }
  return json;
}

/** Collapse duplicate `| null`/`| undefined` union members Modelina emits for nullable type arrays. */
export function dedupeUnions(source) {
  return source.replace(
    /^(\s*[\w"']+\??:\s*)(.+);$/gm,
    (line, prefix, type) => {
      if (!type.includes(" | ")) return line;
      const seen = new Set();
      const parts = type.split(" | ").filter((part) => {
        if (seen.has(part)) return false;
        seen.add(part);
        return true;
      });
      return `${prefix}${parts.join(" | ")};`;
    }
  );
}

export function tidyModelSource(source) {
  let out = dedupeUnions(source)
    // Represent `additionalProperties: true` as a real index signature.
    .replace(
      /^\s*additionalProperties\?: Record<string, any>;$/m,
      "  [key: string]: unknown;"
    )
    .trimStart();
  // Interfaces and type aliases are type-only: `isolatedModules` requires
  // `export type` for their re-export, and a sibling model is imported for its
  // type alone — `verbatimModuleSyntax` rejects a value import of one.
  if (!/\benum\s+\w+/.test(out)) {
    out = out.replace(
      /^import \{(.+)\} from '(\.\/[^']+)';$/gm,
      "import type {$1} from '$2';"
    );
    out = out.replace(/^export \{ (\w+) \};?$/m, "export type { $1 };");
  }
  return out;
}

/**
 * The Modelina setup both model passes share.
 *
 * `enumType: "union"` because an enum member is *nominal*: a cable message is
 * usually the same component a REST schema documents, so `StatusEnum.STARTED`
 * from these models would not be assignable to the literal union an OpenAPI
 * client generates for the very same values, and every payload handed on to
 * code typed by that client would need a cast.
 */
function modelGenerator() {
  return new TypeScriptFileGenerator({
    modelType: "interface",
    mapType: "record",
    enumType: "union",
    // Preserve the snake_case wire keys (user_id, error_message) instead of
    // camelizing — cable payloads are not transformed on the socket path.
    // Keep the default reserved-word/special-char safety, override only casing.
    constraints: {
      propertyKey: typeScriptDefaultPropertyKeyConstraints({
        NAMING_FORMATTER: (name) => name,
        // Interface property names may be any string; keeping wire keys like
        // `status`/`name` verbatim is safe and required to match the payload.
        NO_RESERVED_KEYWORDS: (name) => name,
      }),
    },
  });
}

async function generateModels(document, absModelsDir) {
  const generator = modelGenerator();
  const input = stripConditionals(structuredClone(document.json()));
  const models = await generator.generateToFiles(input, absModelsDir, {
    exportType: "named",
  });

  await tidyModelFiles(models, absModelsDir);

  return models.map((m) => m.modelName);
}

async function tidyModelFiles(models, absModelsDir) {
  for (const model of models) {
    const file = path.join(absModelsDir, `${model.modelName}.ts`);
    const src = await fs.readFile(file, "utf8");
    await fs.writeFile(file, `${BANNER}\n${tidyModelSource(src)}`);
  }
}

/**
 * Models for every component a payload's `contentSchema` points at.
 *
 * Generated in a second pass from a standalone JSON Schema: Modelina's
 * AsyncAPI processor only walks message payloads, so these components are
 * invisible to it no matter how the document references them.
 */
async function generateContentSchemaModels(documentJson, absModelsDir, existing) {
  const generator = modelGenerator();

  const generated = [];
  const seen = new Set(existing);

  for (const target of contentSchemaTargets(documentJson)) {
    const component = target.component;
    if (seen.has(component)) continue;

    const schema = contentSchemaDocument(target.schema, component);
    if (!schema) continue;

    const models = await generator.generateToFiles(
      stripConditionals(schema),
      absModelsDir,
      {exportType: "named"}
    );
    await tidyModelFiles(models, absModelsDir);

    for (const model of models) {
      if (seen.has(model.modelName)) continue;
      seen.add(model.modelName);
      generated.push(model.modelName);
    }
  }

  return generated;
}

/** One `parseXPayload` module per contentSchema target. */
async function generatePayloadParsers(documentJson, absPayloadsDir, modelNames) {
  const targets = contentSchemaTargets(documentJson);
  if (targets.length === 0) return [];

  await fs.mkdir(absPayloadsDir, {recursive: true});

  const written = [];
  for (const target of targets) {
    const source = renderPayloadParser({
      ...target,
      message: matchModelName(target.message, modelNames) ?? target.message,
      component: matchModelName(target.component, modelNames) ?? target.component,
    });
    const name = /export function (\w+)/.exec(source)[1];
    await fs.writeFile(
      path.join(absPayloadsDir, `${name}.ts`),
      `${BANNER}\n${source}`
    );
    written.push(name);
  }

  return written;
}

/**
 * Message payloads that carry a JSON string with a declared decoded shape.
 *
 * A cable payload is sometimes a string — the presence channels embed a
 * rendered REST response the client parses. `contentSchema` is the standard way
 * to say what the decoded value looks like, but Modelina walks message payloads
 * and never follows it, so those components would reach no client.
 *
 * The parser dereferences `$ref`s before we see them, so the component name
 * comes from `x-parser-schema-id`, which it preserves. An inlined anonymous
 * schema has no name to generate under and is skipped; `$ref` is read as a
 * fallback for a document that was never parsed.
 *
 * Returns `{ message, property, component, required, schema }` per occurrence,
 * so a caller can emit the model and know which field to parse.
 */
export function contentSchemaTargets(documentJson) {
  const schemas = documentJson?.components?.schemas ?? {};
  const targets = [];

  for (const [message, definition] of Object.entries(schemas)) {
    for (const [property, node] of Object.entries(definition?.properties ?? {})) {
      const content = node?.contentSchema;
      if (!content) continue;

      const component =
        content["x-parser-schema-id"] ?? refName(content.$ref);
      if (!component || component.startsWith("<anonymous")) continue;

      targets.push({
        message,
        property,
        component,
        required: (definition.required ?? []).includes(property),
        schema: content,
      });
    }
  }

  return targets;
}

/** `#/components/schemas/Foo` -> `Foo`; anything else -> undefined. */
export function refName(pointer) {
  const match = /^#\/components\/schemas\/(\w+)$/.exec(pointer ?? "");
  return match?.[1];
}

/**
 * A `contentSchema` subtree as its own JSON Schema, so Modelina can generate it
 * outside the AsyncAPI processor (which only walks message payloads).
 *
 * The parser has already inlined every `$ref` inside it, so nothing needs
 * resolving — only a name to generate under.
 */
export function contentSchemaDocument(schema, componentName) {
  if (!schema) return undefined;

  return {
    $schema: "http://json-schema.org/draft-07/schema#",
    ...nameNestedSchemas(schema),
    $id: componentName,
  };
}

/**
 * Carries the parser's component names into `$id`.
 *
 * `x-parser-schema-id` is an AsyncAPI-parser convention; Modelina's JSON Schema
 * path ignores it and names a nested model after the property that holds it —
 * a `kind` property yields `Kind`, which is both uninformative and prone to
 * collide across payloads. `$id` is what that path does read.
 */
export function nameNestedSchemas(node) {
  if (Array.isArray(node)) return node.map(nameNestedSchemas);
  if (node === null || typeof node !== "object") return node;

  const named = Object.fromEntries(
    Object.entries(node).map(([key, value]) => [key, nameNestedSchemas(value)])
  );
  const parserId = node["x-parser-schema-id"];
  const nameable =
    typeof parserId === "string" &&
    !parserId.startsWith("<anonymous") &&
    named.$id === undefined;

  return nameable ? {...named, $id: parserId} : named;
}

/** `parseXPayload` helper source for one contentSchema target. */
export function renderPayloadParser({ message, property, component, required }) {
  const fnName = `parse${message}${property.replace(/(^|_)(\w)/g, (_, __, c) => c.toUpperCase())}`;
  const returnType = required ? component : `${component} | undefined`;
  const guard = required
    ? ""
    : `  if (message.${property} === undefined) return undefined;\n`;

  return `import type {${message}} from '../models/${message}';
import type {${component}} from '../models/${component}';

/**
 * Decodes the JSON string in \`${message}.${property}\`.
 *
 * The wire value is a string; the contract declares its decoded shape through
 * \`contentSchema\`. Generated so the cast lives in one place instead of at
 * every call site.
 */
export function ${fnName}(message: ${message}): ${returnType} {
${guard}  return JSON.parse(message.${property} as string) as ${component};
}
`;
}

/** Read an `x-` extension off a parser node, tolerating either json() or the extensions API. */
function extension(node, name) {
  const fromJson = node.json?.()?.[name];
  if (fromJson !== undefined) return fromJson;
  return node.extensions?.().get?.(name)?.value?.();
}

/** Build the TS type for the params the client passes at subscribe time (AsyncAPI 3.0 params are strings). */
export function clientParamsType(channelJson) {
  const params = channelJson?.parameters ?? {};
  const clientParams = Object.keys(params).filter(
    (name) => params[name]?.["x-client-supplied"] !== false
  );
  if (clientParams.length === 0) return "Record<string, never>";
  return `{ ${clientParams.map((name) => `${name}: string`).join("; ")} }`;
}

/**
 * Render the portable AnyCable channel class. Pure — depends only on
 * @anycable/core + the generated message types, so it is extractable and works
 * on any platform (web, React Native).
 */
export function renderChannelClass({
  channelName,
  identifier,
  paramsType,
  messageNames,
}) {
  const className = `${channelName}Channel`;
  const dataType = `${channelName}Data`;
  const paramsName = `${channelName}Params`;
  const modelImports = messageNames
    .map((name) => `import type { ${name} } from "../models/${name}";`)
    .join("\n");

  const source = `${BANNER}
import { Channel } from "@anycable/core";
${modelImports}

/** Alternatives declared for the operation — AsyncAPI treats a channel's messages as a union. */
export type ${dataType} = ${messageNames.join(" | ")};

/** Params the client supplies at subscribe time. */
export type ${paramsName} = ${paramsType};

export class ${className} extends Channel<${paramsName}, ${dataType}> {
  static identifier = "${identifier}";
}
`;

  return { className, dataType, paramsName, source };
}

/** Render the per-channel Vue composable — thin sugar over runtime.subscribeChannel. */
export function renderComposable({
  channelName,
  className,
  dataType,
  paramsName,
  hasParams,
  preset,
}) {
  const composableName = `use${channelName}Channel`;
  const paramsArg = hasParams ? `params: ${paramsName}, ` : "";
  const paramsPass = hasParams ? "params" : "";
  // The params type has to be imported alongside the data type, or the emitted
  // module references a name it never pulled in. Generation still succeeds —
  // only a type-check on the output catches it.
  const typeImports = hasParams
    ? `type ${dataType}, type ${paramsName}`
    : `type ${dataType}`;

  if (preset === "react") {
    const source = `${BANNER}
import { useChannelSubscription, type ChannelHandlers } from "../runtime";
import { ${className}, ${typeImports} } from "../channels/${className}";

/** Subscribe to ${className} for the lifetime of the component. */
export function ${composableName}(
  ${paramsArg}handlers: ChannelHandlers<${dataType}>,
): void {
  useChannelSubscription(() => new ${className}(${paramsPass}), handlers);
}
`;
    return { composableName, source };
  }

  const source = `${BANNER}
import { subscribeChannel, type ChannelHandlers } from "../runtime";
import { ${className}, ${typeImports} } from "../channels/${className}";

/** Subscribe to ${className} for the lifetime of the current effect scope. */
export function ${composableName}(
  ${paramsArg}handlers: ChannelHandlers<${dataType}>,
): ${className} {
  return subscribeChannel(new ${className}(${paramsPass}), handlers);
}
`;

  return { composableName, source };
}

const constrainModelName = typeScriptDefaultModelNameConstraints();

/**
 * Match a name from the document against the emitted model names.
 *
 * Modelina renames a model whose name TypeScript will not take — a message
 * named `Import` is emitted as `ReservedImport`, `2fast` as `Number_2fast` —
 * so a name that does not match verbatim is put through the same constraint
 * before giving up, or the channel imports a module nobody wrote.
 */
export function matchModelName(name, modelNames) {
  if (modelNames.includes(name)) return name;
  const constrained = constrainModelName({ modelName: name });
  return modelNames.includes(constrained) ? constrained : undefined;
}

/** Match an operation message to the Modelina-generated model name for its payload. */
function resolveMessageModelName(message, modelNames) {
  const candidates = [message.id?.(), message.name?.()].filter(Boolean);
  for (const candidate of candidates) {
    const match = matchModelName(candidate, modelNames);
    if (match) return match;
  }
  const payload = message.payload?.();
  const payloadId = payload?.id?.() ?? payload?.$id?.();
  if (payloadId) {
    const match = matchModelName(payloadId, modelNames);
    if (match) return match;
  }
  return candidates[0] ?? payloadId;
}

/** Emit a portable channel class + a per-channel composable/hook per `receive` operation. */
async function generateChannels(
  document,
  absChannelsDir,
  absComposablesDir,
  modelNames,
  preset
) {
  await fs.mkdir(absChannelsDir, { recursive: true });
  await fs.mkdir(absComposablesDir, { recursive: true });
  const emitted = [];

  for (const operation of document.operations().all()) {
    if (operation.action() !== "receive") continue;

    const channel = operation.channels().all()[0];
    const channelName = channel.id();
    const channelJson = channel.json();
    const identifier =
      extension(channel, "x-actioncable-channel") ?? `${channelName}Channel`;
    const paramsType = clientParamsType(channelJson);
    const hasParams = paramsType !== "Record<string, never>";

    const messageNames = operation
      .messages()
      .all()
      .map((message) => resolveMessageModelName(message, modelNames))
      .filter(Boolean);

    const cls = renderChannelClass({
      channelName,
      identifier,
      paramsType,
      messageNames,
    });
    await fs.writeFile(
      path.join(absChannelsDir, `${cls.className}.ts`),
      cls.source
    );

    const comp = renderComposable({
      channelName,
      className: cls.className,
      dataType: cls.dataType,
      paramsName: cls.paramsName,
      hasParams,
      preset,
    });
    await fs.writeFile(
      path.join(absComposablesDir, `${comp.composableName}.ts`),
      comp.source
    );

    emitted.push({
      className: cls.className,
      composableName: comp.composableName,
    });
  }

  return emitted;
}

async function writeBarrel(absOutDir, modelNames, channels, payloadParsers = []) {
  const lines = [
    ...modelNames.map((name) => `export * from "./models/${name}";`),
    ...channels.map((c) => `export * from "./channels/${c.className}";`),
    'export * from "./runtime";',
    ...channels.map(
      (c) => `export * from "./composables/${c.composableName}";`
    ),
    ...payloadParsers.map((name) => `export * from "./payloads/${name}";`),
  ];
  await fs.writeFile(
    path.join(absOutDir, "index.ts"),
    `${BANNER}\n${lines.join("\n")}\n`
  );
}

export async function generateOne({
  input,
  outDir,
  cable = DEFAULT_CABLE,
  preset = "vue",
  cwd = process.cwd(),
}) {
  // A URL input is fetched as-is; a local path is resolved against cwd
  // (`path.resolve` passes absolute paths through, so tests can target a tmp dir).
  const absInput = isRemoteInput(input) ? input : path.resolve(cwd, input);
  const absOutDir = path.resolve(cwd, outDir);

  await fs.rm(absOutDir, { recursive: true, force: true });
  await fs.mkdir(path.join(absOutDir, "models"), { recursive: true });

  const document = await parseDocument(absInput);
  const documentJson = document.json();
  const modelNames = await generateModels(
    document,
    path.join(absOutDir, "models")
  );
  modelNames.push(
    ...(await generateContentSchemaModels(
      documentJson,
      path.join(absOutDir, "models"),
      modelNames
    ))
  );
  const channels = await generateChannels(
    document,
    path.join(absOutDir, "channels"),
    path.join(absOutDir, "composables"),
    modelNames,
    preset
  );
  await fs.writeFile(
    path.join(absOutDir, "runtime.ts"),
    renderRuntime(cable, preset)
  );
  const payloadParsers = await generatePayloadParsers(
    documentJson,
    path.join(absOutDir, "payloads"),
    modelNames
  );
  await writeBarrel(absOutDir, modelNames, channels, payloadParsers);

  console.info(
    `[asyncapi-cable] ${input} -> ${outDir} ` +
      `(${modelNames.length} models, ${channels.length} channels, ` +
      `${payloadParsers.length} payload parsers, ${preset})`
  );
}

/** Generate every target in a config object (see cable.config.mjs), resolving paths against `cwd`. */
export async function generateAll(config, cwd = process.cwd()) {
  for (const target of Object.values(config)) {
    await generateOne({
      input: target.input,
      outDir: target.output.target,
      cable: target.output.cable ?? DEFAULT_CABLE,
      preset: target.output.preset ?? "vue",
      cwd,
    });
  }
}
